# Generated by Django 5.2.7 on 2025-10-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('programme', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('goal', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_started', models.DateField()),
                ('date_completed', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
